---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pod-forward-backend
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`10.1.1.30`) && PathPrefix(`/api/v1/extensions/pod-forward`)
      kind: Rule
      services:
        - name: pod-forward-backend
          port: 8080
  tls:
    secretName: argocd-server-tls
